// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using engenharia_de_software_pb.Data;

#nullable disable

namespace engenharia_de_software_pb.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.ClassPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BehaviorGrade")
                        .HasColumnType("int");

                    b.Property<int>("HomeworkGrade")
                        .HasColumnType("int");

                    b.Property<int>("NotasId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipationGrade")
                        .HasColumnType("int");

                    b.Property<int>("PresenceGrade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotasId")
                        .IsUnique();

                    b.ToTable("ClassPerformances");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.Notas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int?>("GrammarId")
                        .HasColumnType("int");

                    b.Property<int?>("ListeningId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroTeste")
                        .HasColumnType("int");

                    b.Property<int?>("ReadingId")
                        .HasColumnType("int");

                    b.Property<int?>("WritingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("GrammarId");

                    b.HasIndex("ListeningId");

                    b.HasIndex("ReadingId");

                    b.HasIndex("WritingId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.NotaSimples", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NotasId")
                        .HasColumnType("int");

                    b.Property<double>("PrimeiraNota")
                        .HasColumnType("float");

                    b.Property<double>("SegundaNota")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NotasId");

                    b.ToTable("NotaSimples");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.Speaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccuracyGrade")
                        .HasColumnType("int");

                    b.Property<int>("L2Use")
                        .HasColumnType("int");

                    b.Property<int>("LanguageRangeGrade")
                        .HasColumnType("int");

                    b.Property<int>("NotasId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionAndFluencyGrade")
                        .HasColumnType("int");

                    b.Property<int>("SpokenInteractionGrade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotasId")
                        .IsUnique();

                    b.ToTable("Speakings");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.ClassPerformance", b =>
                {
                    b.HasOne("engenharia_de_software_pb.BLL.Models.Notas", "Notas")
                        .WithOne("ClassPerformance")
                        .HasForeignKey("engenharia_de_software_pb.BLL.Models.ClassPerformance", "NotasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.Notas", b =>
                {
                    b.HasOne("engenharia_de_software_pb.BLL.Models.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId");

                    b.HasOne("engenharia_de_software_pb.BLL.Models.NotaSimples", "Grammar")
                        .WithMany()
                        .HasForeignKey("GrammarId");

                    b.HasOne("engenharia_de_software_pb.BLL.Models.NotaSimples", "Listening")
                        .WithMany()
                        .HasForeignKey("ListeningId");

                    b.HasOne("engenharia_de_software_pb.BLL.Models.NotaSimples", "Reading")
                        .WithMany()
                        .HasForeignKey("ReadingId");

                    b.HasOne("engenharia_de_software_pb.BLL.Models.NotaSimples", "Writing")
                        .WithMany()
                        .HasForeignKey("WritingId");

                    b.Navigation("Aluno");

                    b.Navigation("Grammar");

                    b.Navigation("Listening");

                    b.Navigation("Reading");

                    b.Navigation("Writing");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.NotaSimples", b =>
                {
                    b.HasOne("engenharia_de_software_pb.BLL.Models.Notas", "Notas")
                        .WithMany()
                        .HasForeignKey("NotasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.Speaking", b =>
                {
                    b.HasOne("engenharia_de_software_pb.BLL.Models.Notas", "Notas")
                        .WithOne("Speaking")
                        .HasForeignKey("engenharia_de_software_pb.BLL.Models.Speaking", "NotasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.Aluno", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("engenharia_de_software_pb.BLL.Models.Notas", b =>
                {
                    b.Navigation("ClassPerformance");

                    b.Navigation("Speaking");
                });
#pragma warning restore 612, 618
        }
    }
}
